# Generated by Django 2.2.5 on 2019-09-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=100)),
                ('released', models.CharField(max_length=100)),
                ('background_image', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('ratings_count', models.CharField(max_length=100)),
                ('playtime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=500)),
                ('url_en', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_screenshots', to='games.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.Store'),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.CharField(max_length=500)),
                ('game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clip', to='games.Game')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('name', 'released')},
        ),
    ]
