# Generated by Django 2.2.5 on 2019-09-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirements',
            new_name='Requirement',
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
