# Generated by Django 2.2.5 on 2019-09-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='description',
            new_name='description_raw',
        ),
    ]
