# Generated by Django 2.2.5 on 2019-09-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
