# Generated by Django 2.2.5 on 2019-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190907_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='website',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
