# Generated by Django 2.2.5 on 2019-09-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='website',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
