# Generated by Django 2.2.5 on 2019-09-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20190904_1540'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('name', 'released')},
        ),
    ]
